### ISSUE TITLE
Raven needs to be installed

### ISSUE THREAD

**Issue by Tina9** [lvrcek/NeuralLayout#2]
Hello,

I am trying to test this model on some other reads in FASTQ format. However, when I run the command, there is an error.
<img width="1491" alt="Screenshot 2022-04-18 at 4 58 21 PM" src="https://user-images.githubusercontent.com/16876314/163785451-ce678a10-a650-4055-b1c7-93af2570714d.png">

Then I went to ./vendor/raven/build, and found
<img width="854" alt="Screenshot 2022-04-18 at 5 07 24 PM" src="https://user-images.githubusercontent.com/16876314/163785669-3c08fb0c-57ee-43ec-a8ff-e77f96aecff6.png">

Hence, we need to install Raven first, right?

Thanks for your help at first.

**Comment by lvrcek** [comment]
Hi,

Yes, if you want to use Raven, you should also download and install Raven.
You can find the instructions below.

First download the code:
```bash
git clone --recursive https://github.com/lvrcek/NeuralLayout.git
cd NeuralLayout
```

Create the virtual environment:
```bash
python -m venv env
source env/bin/activate
```

Install the requirements:
```bash
pip install -r requirements.txt
```

If you want to use Raven for creating the graphs from raw genomic reads in FASTQ format, run the following script.
If not, you can skip this part.
```bash
source setup.sh
```

If you did all this, did you maybe forget to put `--recursive` for `git clone` while downloading the repo? This might be the reason that the Raven is not installed.

**Comment by Tina9** [comment]
Got it. Thanks for your reply.

**Comment by lvrcek** [comment]
Let me know if you encounter some further issues.
